export const TEKION_GET_DEALER_INFO = 'TEKION_GET_DEALER_INFO';
export const TEKION_DEALER_INFO_REQUEST = 'TEKION_DEALER_INFO_REQUEST';
export const TEKION_DEALER_INFO_SUCCESS = 'TEKION_DEALER_INFO_SUCCESS';
export const TEKION_DEALER_INFO_FAILURE = 'TEKION_DEALER_INFO_FAILURE';
