export const TEKION_GET_DEALER_INFO = 'TEKION_GET_DEALER_INFO';
export const TEKION_DEALER_INFO_REQUEST = 'TEKION_DEALER_INFO_REQUEST';
export const TEKION_DEALER_INFO_SUCCESS = 'TEKION_DEALER_INFO_SUCCESS';
export const TEKION_DEALER_INFO_FAILURE = 'TEKION_DEALER_INFO_FAILURE';

export const TEKION_GET_FIXED_OPERATION_REQUEST =
  'TEKION_GET_FIXED_OPERATION_REQUEST';
export const TEKION_GET_FIXED_OPERATION_SUCCESS =
  'TEKION_GET_FIXED_OPERATION_SUCCESS';
export const TEKION_GET_FIXED_OPERATION_FAILURE =
  'TEKION_GET_FIXED_OPERATION_FAILURE';

export const TEKION_DEALER_LIST_REQUEST = 'TEKION_DEALER_LIST_REQUEST';
export const TEKION_DEALER_LIST_SUCCESS = 'TEKION_DEALER_LIST_SUCCESS';
export const TEKION_DEALER_LIST_FAILURE = 'TEKION_DEALER_LIST_FAILURE';

export const TEKION_UPDATE_DEALER_INFO_REQUEST =
  'TEKION_UPDATE_DEALER_INFO_REQUEST';
export const TEKION_UPDATE_DEALER_INFO_SUCCESS =
  'TEKION_UPDATE_DEALER_INFO_SUCCESS';
export const TEKION_UPDATE_DEALER_INFO_FAILURE =
  'TEKION_UPDATE_DEALER_INFO_FAILURE';

export const TEKION_CREATE_DEALER_REQUEST = 'TEKION_CREATE_DEALER_REQUEST';
export const TEKION_CREATE_DEALER_SUCCESS = 'TEKION_CREATE_DEALER_SUCCESS';
export const TEKION_CREATE_DEALER_FAILURE = 'TEKION_CREATE_DEALER_FAILURE';

export const TEKION_DEALER_RESET_STATE = 'TEKION_DEALER_RESET_STATE';

export const TEKION_GET_LABORTYPES_FOR_MAKE = 'TEKION_GET_LABORTYPES_FOR_MAKE';
