export const TEKION_DEALER_CREATE_REQUEST = "TEKION_DEALER_CREATE_REQUEST";
export const TEKION_DEALER_CREATE_SUCCESS = "TEKION_DEALER_CREATE_SUCCESS";
export const TEKION_DEALER_CREATE_FAILURE = "TEKION_DEALER_CREATE_FAILURE";
